= Let’s develop on Prod! Wait! What?!

== Abstract

Do you have confidence that your Test and Stage environments reflect reality? Are they easy to keep up-to-date with production? Can you reproduce production failure in these environments or locally? What about that error you keep seeing on production that’s never occurring on Test or Stage?

It's been always hard to test new functionality before it reaches production. Even more so, with the shift from a monolith to microservices and increasing scale. Can you still spin up the entire solution on your laptop to debug and test a suspicious piece of code? Testing on production is no longer a meme. It’s reality and a necessity.

Let's talk about how we can leverage Istio and Kubernetes or Openshift to be confident that changes won't blow up your production cluster and your users won’t even notice a glitch.

Join this session to learn how to safely develop and test your services in a real production environment. Leave with tools and techniques you can apply right away and with confidence!


== Concept

. I want to start with looking at how "cloud native" and new infrastructures such as containers and k8s together with microservices, while simplifying operation side of things, bring new challenges for developer's day-to-day work in contrast to good, old monoliths ;) 
. Next, I will dive to tools which are trying to address this problem space, starting from debugging (solo.io squash), shorter inner-loop cycles (skaffold from Google and VS Code remote development) to running your service locally but interacting with the whole cluster through normal flow (telepresence.io) 
. The main part of the presentation (and demos) is the tool we are working on, which leverages some of the solutions mentioned above, but combining it with service mesh let you develop on a live cluster without affecting regular user base (one can think of it as A/B testing but with live development) 